import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1780315929443 implements MigrationInterface {
    name = 'InitialSchema1780315929443'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "form_field" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "organization_id" character varying NOT NULL, "campaign_id" uuid NOT NULL, "label" character varying NOT NULL, "field_key" character varying NOT NULL, "field_type" character varying NOT NULL, "placeholder" character varying, "is_required" boolean NOT NULL DEFAULT false, "sort_order" integer NOT NULL DEFAULT '0', "options" jsonb, "validation" jsonb, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_135904ddb60085b07254ea4f485" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c3d30edd6a618844bfdd37c236" ON "form_field"  ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_field_key_per_campaign" ON "form_field"  ("campaign_id", "field_key") `);
        await queryRunner.query(`CREATE TABLE "form_submission_value" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "organization_id" character varying NOT NULL, "submission_id" uuid NOT NULL, "field_id" uuid NOT NULL, "field_key" character varying NOT NULL, "value" text, "file_url" character varying, CONSTRAINT "PK_bfe03a7326baed4fb7a056149c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_603b9a9277ae1f36ca7cbb8dbc" ON "form_submission_value"  ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_value_per_field" ON "form_submission_value"  ("submission_id", "field_id") `);
        await queryRunner.query(`CREATE TABLE "form_submission" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "organization_id" character varying NOT NULL, "campaign_id" uuid NOT NULL, "respondent_name" character varying, "respondent_email" character varying NOT NULL, "is_registered" boolean NOT NULL DEFAULT true, "submitted_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_afdf6f86e3747141dd75876e027" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_48b012ab461aab0019ce957bd3" ON "form_submission"  ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_email_per_campaign" ON "form_submission"  ("campaign_id", "respondent_email") `);
        await queryRunner.query(`CREATE TABLE "campaign" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "organization_id" character varying NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "cover_image_url" character varying, "event_date" TIMESTAMP, "location" character varying, "status" character varying NOT NULL DEFAULT 'draft', "qr_code_token" character varying NOT NULL, "qr_code_url" character varying, "attendance_open_at" TIMESTAMP, "attendance_close_at" TIMESTAMP, CONSTRAINT "UQ_4972723fede76ac2d46e37c3e8e" UNIQUE ("qr_code_token"), CONSTRAINT "PK_0ce34d26e7f2eb316a3a592cdc4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8e2fbfe1fc6dc632c4631a1224" ON "campaign"  ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_campaign_org_slug" ON "campaign"  ("organization_id", "slug") `);
        await queryRunner.query(`CREATE TABLE "session" ("id" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "token" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "ipAddress" character varying, "userAgent" character varying, "userId" character varying NOT NULL, "activeOrganizationId" character varying, CONSTRAINT "UQ_232f8e85d7633bd6ddfad421696" UNIQUE ("token"), CONSTRAINT "PK_f55da76ac1c3ac420f444d2ff11" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "account" ("id" character varying NOT NULL, "accountId" character varying NOT NULL, "providerId" character varying NOT NULL, "userId" character varying NOT NULL, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" TIMESTAMP, "refreshTokenExpiresAt" TIMESTAMP, "scope" character varying, "password" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_54115ee388cdb6d86bb4bf5b2ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" character varying NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, "emailVerified" boolean NOT NULL DEFAULT false, "image" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "is_superadmin" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attendance_record" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "organization_id" character varying NOT NULL, "campaign_id" uuid NOT NULL, "submission_id" uuid NOT NULL, "scanned_at" TIMESTAMP NOT NULL DEFAULT now(), "method" character varying NOT NULL DEFAULT 'qr', "marked_by" character varying, "device_info" character varying, CONSTRAINT "PK_c23131acc63826e373019447965" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_962ed13656d1c6d096a775a037" ON "attendance_record"  ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_attendance_per_submission" ON "attendance_record"  ("campaign_id", "submission_id") `);
        await queryRunner.query(`CREATE TABLE "qr_scan_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "organization_id" character varying NOT NULL, "campaign_id" uuid NOT NULL, "qr_code_token" character varying NOT NULL, "scanned_at" TIMESTAMP NOT NULL DEFAULT now(), "device_info" character varying, "is_valid_registrant" boolean NOT NULL, "submission_id" uuid, CONSTRAINT "PK_3df7f031cbcc25bfdee47f3626a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_86a8698c3ace3cb3e92dba0509" ON "qr_scan_log"  ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "activity_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "organization_id" character varying NOT NULL, "actor_user_id" character varying, "share_link_id" character varying, "campaign_id" character varying, "action" character varying NOT NULL, "resource_type" character varying, "resource_id" character varying, "metadata" jsonb, "ip_address" character varying, CONSTRAINT "PK_067d761e2956b77b14e534fd6f1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eb6630f3f614e4cfec203d32ce" ON "activity_log"  ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "email_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "organization_id" character varying NOT NULL, "delivery_job_id" uuid NOT NULL, "submission_id" uuid NOT NULL, "campaign_id" uuid NOT NULL, "recipient_name" character varying, "recipient_email" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "sent_at" TIMESTAMP, "error_message" text, "retry_count" integer NOT NULL DEFAULT '0', "certificate_file_url" character varying, CONSTRAINT "PK_edfd3f7225051fc07bdd63a22dc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e2470abde848694fbe86656eb5" ON "email_log"  ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "idx_emaillog_status" ON "email_log"  ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_email_per_job" ON "email_log"  ("delivery_job_id", "submission_id") `);
        await queryRunner.query(`CREATE TABLE "delivery_job" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "organization_id" character varying NOT NULL, "campaign_id" uuid NOT NULL, "triggered_by" character varying NOT NULL, "target_filter" character varying NOT NULL, "total_target" integer NOT NULL DEFAULT '0', "total_sent" integer NOT NULL DEFAULT '0', "total_success" integer NOT NULL DEFAULT '0', "total_failed" integer NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'pending', "started_at" TIMESTAMP, "completed_at" TIMESTAMP, "celery_task_id" character varying, "error_summary" text, CONSTRAINT "PK_783eb6cb417de97d8823a2a1a9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4a4f48d40e62c8ab18fd7fc793" ON "delivery_job"  ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "verification" ("id" character varying NOT NULL, "identifier" character varying NOT NULL, "value" character varying NOT NULL, "expires_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f7e3a90ca384e71d6e2e93bb340" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "share_link" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "organization_id" character varying NOT NULL, "campaign_id" uuid NOT NULL, "created_by" character varying NOT NULL, "token" character varying NOT NULL, "resource_type" character varying NOT NULL, "permission" character varying NOT NULL DEFAULT 'edit', "label" character varying, "is_active" boolean NOT NULL DEFAULT true, "expires_at" TIMESTAMP, "last_accessed_at" TIMESTAMP, "access_count" integer NOT NULL DEFAULT '0', "revoked_at" TIMESTAMP, "revoked_by" character varying, CONSTRAINT "PK_c20801720fbd00896c634d4aa94" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_85d0b3734454eb92b9a74d78e9" ON "share_link"  ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_sharelink_token" ON "share_link"  ("token") `);
        await queryRunner.query(`CREATE TABLE "member" ("id" character varying NOT NULL, "organizationId" character varying NOT NULL, "userId" character varying NOT NULL, "role" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_97cbbe986ce9d14ca5894fdc072" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_org_member" ON "member"  ("organizationId", "userId") `);
        await queryRunner.query(`CREATE TABLE "organization" ("id" character varying NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "logo" character varying, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "plan" character varying NOT NULL DEFAULT 'free', "email_quota_limit" integer NOT NULL DEFAULT '500', "email_quota_used" integer NOT NULL DEFAULT '0', "quota_reset_at" TIMESTAMP, "is_active" boolean NOT NULL DEFAULT true, "sender_email" character varying, "sender_name" character varying, CONSTRAINT "UQ_a08804baa7c5d5427067c49a31f" UNIQUE ("slug"), CONSTRAINT "PK_472c1f99a32def1b0abb219cd67" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invitation" ("id" character varying NOT NULL, "organizationId" character varying NOT NULL, "email" character varying NOT NULL, "role" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "expiresAt" TIMESTAMP NOT NULL, "inviterId" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_beb994737756c0f18a1c1f8669c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "organization_email_credential" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "organization_id" character varying NOT NULL, "provider" character varying NOT NULL, "google_access_token" text, "google_refresh_token" text, "google_token_expires_at" TIMESTAMP, "smtp_host" character varying, "smtp_port" integer, "smtp_username" character varying, "smtp_password" text, "smtp_secure" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_e41df890ddfd8bb48e9d98d045b" UNIQUE ("organization_id"), CONSTRAINT "REL_e41df890ddfd8bb48e9d98d045" UNIQUE ("organization_id"), CONSTRAINT "PK_99971748c54d09eaa57b8ed9674" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "certificate_template" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "organization_id" character varying NOT NULL, "campaign_id" uuid NOT NULL, "background_image_url" character varying NOT NULL, "output_format" character varying NOT NULL DEFAULT 'pdf', "width_px" integer NOT NULL DEFAULT '2480', "height_px" integer NOT NULL DEFAULT '1754', "last_edited_by" character varying, CONSTRAINT "UQ_504acfd08f13504bcbccd8dc7d7" UNIQUE ("campaign_id"), CONSTRAINT "REL_504acfd08f13504bcbccd8dc7d" UNIQUE ("campaign_id"), CONSTRAINT "PK_ebcee895a1bd52ba466be9669ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9725baabcf81aabfe0bb6c3148" ON "certificate_template"  ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "certificate_element" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "organization_id" character varying NOT NULL, "certificate_template_id" uuid NOT NULL, "element_type" character varying NOT NULL, "label" character varying NOT NULL, "variable" character varying, "static_text" character varying, "font_family" character varying NOT NULL DEFAULT 'Arial', "font_size" integer NOT NULL DEFAULT '48', "font_color" character varying NOT NULL DEFAULT '#000000', "font_weight" character varying NOT NULL DEFAULT 'normal', "text_align" character varying NOT NULL DEFAULT 'center', "image_url" character varying, "pos_x" integer NOT NULL DEFAULT '0', "pos_y" integer NOT NULL DEFAULT '0', "width" integer, "height" integer, "sort_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_57fb956cc2469158f95f52c4c5c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_806c449e0012dd85885915b776" ON "certificate_element"  ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "email_template" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "organization_id" character varying NOT NULL, "campaign_id" uuid NOT NULL, "subject" character varying, "body_html" text, "confirmation_subject" character varying, "confirmation_body_html" text, "header_image_url" character varying, "header_bg_color" character varying NOT NULL DEFAULT '#ffffff', "footer_text" text, "last_edited_by" character varying, CONSTRAINT "UQ_c8baedd6613d2b2e11ed90a8807" UNIQUE ("campaign_id"), CONSTRAINT "REL_c8baedd6613d2b2e11ed90a880" UNIQUE ("campaign_id"), CONSTRAINT "PK_c90815fd4ca9119f19462207710" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_084761ceeb7782a7bb673ec283" ON "email_template"  ("organization_id") `);
        await queryRunner.query(`ALTER TABLE "form_field" ADD CONSTRAINT "FK_4960ab996c64592e65444f1df49" FOREIGN KEY ("campaign_id") REFERENCES "campaign"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_submission_value" ADD CONSTRAINT "FK_3940947575a380ff5b062d0f7b3" FOREIGN KEY ("submission_id") REFERENCES "form_submission"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_submission_value" ADD CONSTRAINT "FK_7d72a6d7bcefbf3522caaa29a5e" FOREIGN KEY ("field_id") REFERENCES "form_field"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_submission" ADD CONSTRAINT "FK_8112f7bae944a9d21861a1d66ff" FOREIGN KEY ("campaign_id") REFERENCES "campaign"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_3d2f174ef04fb312fdebd0ddc53" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account" ADD CONSTRAINT "FK_60328bf27019ff5498c4b977421" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_record" ADD CONSTRAINT "FK_a067b0f30ba16c797a6a18e111e" FOREIGN KEY ("campaign_id") REFERENCES "campaign"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_record" ADD CONSTRAINT "FK_ac5a8b153d488678f4a90b90418" FOREIGN KEY ("submission_id") REFERENCES "form_submission"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_record" ADD CONSTRAINT "FK_2c78b7330b549eadedc1a83dabb" FOREIGN KEY ("marked_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qr_scan_log" ADD CONSTRAINT "FK_21082a7f99b783c4cfabc7b479a" FOREIGN KEY ("campaign_id") REFERENCES "campaign"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qr_scan_log" ADD CONSTRAINT "FK_ce67175589d225d6a419ba5ed2a" FOREIGN KEY ("submission_id") REFERENCES "form_submission"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_log" ADD CONSTRAINT "FK_eb869e4d1fcca51447ad403ea74" FOREIGN KEY ("delivery_job_id") REFERENCES "delivery_job"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_log" ADD CONSTRAINT "FK_db2323427502c055763112bf357" FOREIGN KEY ("submission_id") REFERENCES "form_submission"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_log" ADD CONSTRAINT "FK_0264a32103c3a93858f99e572db" FOREIGN KEY ("campaign_id") REFERENCES "campaign"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_job" ADD CONSTRAINT "FK_d1613d78c65e166792d43f800fd" FOREIGN KEY ("campaign_id") REFERENCES "campaign"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_job" ADD CONSTRAINT "FK_c6b47005c01f963ac1ecdb9a3c5" FOREIGN KEY ("triggered_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "share_link" ADD CONSTRAINT "FK_fba966392853f35f22ed32cdffd" FOREIGN KEY ("campaign_id") REFERENCES "campaign"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "share_link" ADD CONSTRAINT "FK_49f48a020c517f9f9f7ee80c820" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "share_link" ADD CONSTRAINT "FK_a1867dc054ef1439f329f055d5a" FOREIGN KEY ("revoked_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "member" ADD CONSTRAINT "FK_8122e5920a29af5ef76e2e2ff62" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "member" ADD CONSTRAINT "FK_08897b166dee565859b7fb2fcc8" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitation" ADD CONSTRAINT "FK_5c00d7d515395f91bd1fee19f32" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitation" ADD CONSTRAINT "FK_528426b10830422eac8e5c51e7f" FOREIGN KEY ("inviterId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_email_credential" ADD CONSTRAINT "FK_e41df890ddfd8bb48e9d98d045b" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "certificate_template" ADD CONSTRAINT "FK_504acfd08f13504bcbccd8dc7d7" FOREIGN KEY ("campaign_id") REFERENCES "campaign"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "certificate_template" ADD CONSTRAINT "FK_46efeb79f3f8e8e8de4028207bc" FOREIGN KEY ("last_edited_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "certificate_element" ADD CONSTRAINT "FK_d042a598a233f6764ad7534deee" FOREIGN KEY ("certificate_template_id") REFERENCES "certificate_template"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_template" ADD CONSTRAINT "FK_c8baedd6613d2b2e11ed90a8807" FOREIGN KEY ("campaign_id") REFERENCES "campaign"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_template" ADD CONSTRAINT "FK_4135f94228855664110366e394a" FOREIGN KEY ("last_edited_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "email_template" DROP CONSTRAINT "FK_4135f94228855664110366e394a"`);
        await queryRunner.query(`ALTER TABLE "email_template" DROP CONSTRAINT "FK_c8baedd6613d2b2e11ed90a8807"`);
        await queryRunner.query(`ALTER TABLE "certificate_element" DROP CONSTRAINT "FK_d042a598a233f6764ad7534deee"`);
        await queryRunner.query(`ALTER TABLE "certificate_template" DROP CONSTRAINT "FK_46efeb79f3f8e8e8de4028207bc"`);
        await queryRunner.query(`ALTER TABLE "certificate_template" DROP CONSTRAINT "FK_504acfd08f13504bcbccd8dc7d7"`);
        await queryRunner.query(`ALTER TABLE "organization_email_credential" DROP CONSTRAINT "FK_e41df890ddfd8bb48e9d98d045b"`);
        await queryRunner.query(`ALTER TABLE "invitation" DROP CONSTRAINT "FK_528426b10830422eac8e5c51e7f"`);
        await queryRunner.query(`ALTER TABLE "invitation" DROP CONSTRAINT "FK_5c00d7d515395f91bd1fee19f32"`);
        await queryRunner.query(`ALTER TABLE "member" DROP CONSTRAINT "FK_08897b166dee565859b7fb2fcc8"`);
        await queryRunner.query(`ALTER TABLE "member" DROP CONSTRAINT "FK_8122e5920a29af5ef76e2e2ff62"`);
        await queryRunner.query(`ALTER TABLE "share_link" DROP CONSTRAINT "FK_a1867dc054ef1439f329f055d5a"`);
        await queryRunner.query(`ALTER TABLE "share_link" DROP CONSTRAINT "FK_49f48a020c517f9f9f7ee80c820"`);
        await queryRunner.query(`ALTER TABLE "share_link" DROP CONSTRAINT "FK_fba966392853f35f22ed32cdffd"`);
        await queryRunner.query(`ALTER TABLE "delivery_job" DROP CONSTRAINT "FK_c6b47005c01f963ac1ecdb9a3c5"`);
        await queryRunner.query(`ALTER TABLE "delivery_job" DROP CONSTRAINT "FK_d1613d78c65e166792d43f800fd"`);
        await queryRunner.query(`ALTER TABLE "email_log" DROP CONSTRAINT "FK_0264a32103c3a93858f99e572db"`);
        await queryRunner.query(`ALTER TABLE "email_log" DROP CONSTRAINT "FK_db2323427502c055763112bf357"`);
        await queryRunner.query(`ALTER TABLE "email_log" DROP CONSTRAINT "FK_eb869e4d1fcca51447ad403ea74"`);
        await queryRunner.query(`ALTER TABLE "qr_scan_log" DROP CONSTRAINT "FK_ce67175589d225d6a419ba5ed2a"`);
        await queryRunner.query(`ALTER TABLE "qr_scan_log" DROP CONSTRAINT "FK_21082a7f99b783c4cfabc7b479a"`);
        await queryRunner.query(`ALTER TABLE "attendance_record" DROP CONSTRAINT "FK_2c78b7330b549eadedc1a83dabb"`);
        await queryRunner.query(`ALTER TABLE "attendance_record" DROP CONSTRAINT "FK_ac5a8b153d488678f4a90b90418"`);
        await queryRunner.query(`ALTER TABLE "attendance_record" DROP CONSTRAINT "FK_a067b0f30ba16c797a6a18e111e"`);
        await queryRunner.query(`ALTER TABLE "account" DROP CONSTRAINT "FK_60328bf27019ff5498c4b977421"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_3d2f174ef04fb312fdebd0ddc53"`);
        await queryRunner.query(`ALTER TABLE "form_submission" DROP CONSTRAINT "FK_8112f7bae944a9d21861a1d66ff"`);
        await queryRunner.query(`ALTER TABLE "form_submission_value" DROP CONSTRAINT "FK_7d72a6d7bcefbf3522caaa29a5e"`);
        await queryRunner.query(`ALTER TABLE "form_submission_value" DROP CONSTRAINT "FK_3940947575a380ff5b062d0f7b3"`);
        await queryRunner.query(`ALTER TABLE "form_field" DROP CONSTRAINT "FK_4960ab996c64592e65444f1df49"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_084761ceeb7782a7bb673ec283"`);
        await queryRunner.query(`DROP TABLE "email_template"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_806c449e0012dd85885915b776"`);
        await queryRunner.query(`DROP TABLE "certificate_element"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9725baabcf81aabfe0bb6c3148"`);
        await queryRunner.query(`DROP TABLE "certificate_template"`);
        await queryRunner.query(`DROP TABLE "organization_email_credential"`);
        await queryRunner.query(`DROP TABLE "invitation"`);
        await queryRunner.query(`DROP TABLE "organization"`);
        await queryRunner.query(`DROP INDEX "public"."uq_org_member"`);
        await queryRunner.query(`DROP TABLE "member"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sharelink_token"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85d0b3734454eb92b9a74d78e9"`);
        await queryRunner.query(`DROP TABLE "share_link"`);
        await queryRunner.query(`DROP TABLE "verification"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a4f48d40e62c8ab18fd7fc793"`);
        await queryRunner.query(`DROP TABLE "delivery_job"`);
        await queryRunner.query(`DROP INDEX "public"."uq_email_per_job"`);
        await queryRunner.query(`DROP INDEX "public"."idx_emaillog_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e2470abde848694fbe86656eb5"`);
        await queryRunner.query(`DROP TABLE "email_log"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb6630f3f614e4cfec203d32ce"`);
        await queryRunner.query(`DROP TABLE "activity_log"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_86a8698c3ace3cb3e92dba0509"`);
        await queryRunner.query(`DROP TABLE "qr_scan_log"`);
        await queryRunner.query(`DROP INDEX "public"."uq_attendance_per_submission"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_962ed13656d1c6d096a775a037"`);
        await queryRunner.query(`DROP TABLE "attendance_record"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "account"`);
        await queryRunner.query(`DROP TABLE "session"`);
        await queryRunner.query(`DROP INDEX "public"."idx_campaign_org_slug"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e2fbfe1fc6dc632c4631a1224"`);
        await queryRunner.query(`DROP TABLE "campaign"`);
        await queryRunner.query(`DROP INDEX "public"."uq_email_per_campaign"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48b012ab461aab0019ce957bd3"`);
        await queryRunner.query(`DROP TABLE "form_submission"`);
        await queryRunner.query(`DROP INDEX "public"."uq_value_per_field"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_603b9a9277ae1f36ca7cbb8dbc"`);
        await queryRunner.query(`DROP TABLE "form_submission_value"`);
        await queryRunner.query(`DROP INDEX "public"."uq_field_key_per_campaign"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3d30edd6a618844bfdd37c236"`);
        await queryRunner.query(`DROP TABLE "form_field"`);
    }

}
